### ISSUE TITLE
Support "In Question" type introduced in Xit 1.1

### ISSUE THREAD

**Issue by DLvalentine** [vcsala/xit-extended#1]
The specification for Xit has been updated to include a new item status: "In Question" denoted by a question mark:

`[?] Create mockup for client`

xit-extended does not currently support this.

**Comment by DLvalentine** [comment]
If I have time, I'll try to add it myself, and will open a PR if I do! But I don't have experience with vscode extensions, so it might take me a shake - don't wait up for me lol

**Comment by vcsala** [comment]
I have made the changes, but publishing is not working. It will be published as soon as that issue solved.
